title: KonexHT Digital Solutions
description: "Empowering Haiti's digital future with premium writing, design, literacy, and strategic services."
baseurl: ""
url: "https://konexht.github.io"
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Custom Variables
whatsapp_number: "50931234567"
